version: "2"

run:
  tests: true

output:
  print-issued-lines: false

linters:
  enable-all: true
  disable:
    - gomoddirectives
    - exhaustruct
    - funlen
    - gochecknoglobals
    - gocritic
    - gosec
    - lll
    - mnd
    - paralleltest
    - testpackage
    - varnamelen
    - wrapcheck
    - wsl
    - depguard
    - tagalign
    - tagliatelle
    - ireturn
    - godox
    - err113

formatters:
  disable-all: true

issues:
  max-per-linter: 0
  max-same: 0
